### PR TITLE
Added support for port number input for host testing.

### PR DESCRIPTION
**Pull request by JonBons**

### CODE REVIEW

**Comment by xPaw** [comment]
Good idea, but you're calling parse_url() twice to get the port, I would simply assign $port to parse_url result directly, check if it's null, and reset it to 80.

**Comment by xPaw** [comment]
Will you fix caching, or want me to do it?

**Comment by JonBons** [comment]
Sorry I'm a bit busy right now with support updating servers :( If you don't mind?

**Comment by xPaw** [comment]
Sure, I`ll do it.

**Pull request merged**
